# Generated by Django 2.1.7 on 2019-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200, verbose_name='series_name')),
                ('episode_name', models.CharField(max_length=200, verbose_name='episode_name')),
                ('episode_date', models.DateTimeField(verbose_name='episode_date')),
                ('download_link', models.CharField(max_length=200, verbose_name='download_link')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('date', models.IntegerField(verbose_name='date')),
                ('genres', models.CharField(max_length=200, verbose_name='genres')),
            ],
        ),
    ]
